# Generated by Django 5.2.3 on 2025-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class (e.g. fa-solid fa-code)', max_length=100)),
            ],
        ),
    ]
