# Generated by Django 5.2.3 on 2025-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_service_icon_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('office1_label', models.CharField(max_length=100)),
                ('office1_address', models.TextField()),
                ('office2_label', models.CharField(max_length=100)),
                ('office2_address', models.TextField()),
                ('hours_weekdays', models.CharField(max_length=100)),
                ('hours_saturday', models.CharField(max_length=100)),
                ('hours_sunday', models.CharField(max_length=100)),
            ],
        ),
    ]
