# Generated by Django 5.2.3 on 2025-07-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
