# Generated by Django 5.2.3 on 2025-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_video_youtube_url_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=255, upload_to='videos/'),
        ),
    ]
