# Generated by Django 3.2.25 on 2025-07-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20250704_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_file', models.FileField(max_length=255, upload_to='blog_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('is_organic', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='13 July 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='13 July 2025', max_length=100),
        ),
    ]
