# Generated by Django 5.2.3 on 2025-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_file', models.FileField(upload_to='blog_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
