# Generated by Django 4.2.23 on 2025-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20250713_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Learning Links', max_length=255)),
                ('copyright_text', models.CharField(default='© Learning Links 2025', max_length=255)),
                ('abn', models.CharField(default='ABN: 71 097 577 636', max_length=50)),
                ('donation_note', models.CharField(default='Donations over $2 are tax deductible.', max_length=255)),
                ('child_safe_message', models.TextField()),
                ('child_safe_link', models.URLField(default='#')),
                ('child_safe_link_text', models.CharField(default='Child Safe Policy', max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('bottom_links', models.TextField(blank=True, help_text='Use format: Label|URL (one per line)')),
            ],
        ),
    ]
