# Generated by Django 5.2.3 on 2025-07-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_blogmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='media_file',
            field=models.FileField(max_length=255, upload_to='blog_media/'),
        ),
    ]
