# Generated by Django 4.2.23 on 2025-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_footeroption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Footer', max_length=100)),
                ('support_heading', models.CharField(default='Client Support', max_length=100)),
                ('support_text', models.CharField(max_length=255)),
                ('support_link', models.URLField(default='#')),
                ('reward_heading', models.CharField(default='Reward Us', max_length=100)),
                ('reward_text', models.CharField(max_length=255)),
                ('reward_link', models.URLField(default='#')),
                ('feedback_heading', models.CharField(default='Feedback/Complaints', max_length=100)),
                ('feedback_text', models.CharField(max_length=255)),
                ('feedback_link', models.URLField(default='#')),
                ('contact_heading', models.CharField(default='Contact Us', max_length=100)),
                ('contact_text', models.CharField(max_length=255)),
                ('contact_link', models.URLField(default='#')),
            ],
        ),
    ]
