# Generated by Django 4.2.23 on 2025-07-25 11:22

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_additionalcontent_carouselslide_fundingoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingOptionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Intro Text')),
                ('extra_info', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Extra Info')),
                ('image', models.ImageField(blank=True, null=True, upload_to='funding_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='25 July 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='25 July 2025', max_length=100),
        ),
        migrations.CreateModel(
            name='FundingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('funding_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.fundingoptionpage')),
            ],
        ),
    ]
