# Generated by Django 4.2.23 on 2025-08-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_fundingoptionpage_alter_comment_time_alter_post_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='therapy_methods/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='01 August 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='01 August 2025', max_length=100),
        ),
        migrations.CreateModel(
            name='TherapySubMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='myapp.therapymethod')),
            ],
        ),
    ]
