# Generated by Django 5.2.3 on 2025-08-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_therapymethod_alter_comment_time_alter_post_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFooter',
        ),
        migrations.DeleteModel(
            name='FooterOption',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='12 August 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='12 August 2025', max_length=100),
        ),
    ]
