# Generated by Django 5.2.3 on 2025-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_delete_contactfooter_delete_footeroption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Activ Therapy', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('tagline', models.CharField(default='Live Healthier and Happier for Longer', max_length=255)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('about_heading', models.CharField(default='Activ Therapy', max_length=100)),
                ('about_links', models.TextField(blank=True, help_text='Format: Label|URL (one per line)')),
                ('services_heading', models.CharField(default='Services', max_length=100)),
                ('support_heading', models.CharField(default='Support', max_length=100)),
                ('support_text', models.CharField(default='(02) 9726 4491', max_length=255)),
                ('support_link', models.URLField(default='tel:0297264491')),
                ('book_text', models.CharField(default='Book Now', max_length=255)),
                ('book_link', models.URLField(default='#')),
                ('locations', models.TextField(blank=True, help_text='Format: Label|URL (one per line)')),
                ('copyright_text', models.CharField(default='Copyright ©2024 Activ Therapy', max_length=255)),
                ('bottom_links', models.TextField(blank=True, help_text='Format: Label|URL (one per line)')),
                ('designer_text', models.CharField(default='Locally - Local Experts', max_length=255)),
                ('designer_link', models.URLField(default='#')),
            ],
        ),
    ]
