# Generated by Django 5.2.3 on 2025-08-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_appointmentrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='video_url',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='13 August 2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='fundingdetail',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fundingoptionpage',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundingoptionpage',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='13 August 2025', max_length=100),
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='center', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
